-- ============================================
-- System UI data model (DEPLOY-FIXES §7)
--  - users.settings JSONB: feature flags (`system_ui`, default off) + school
--    theme id
--  - quests: daily / main / side quests; daily generated by 6 AM cron from
--    schedule + open assignments
--  - xp_events: append-only XP ledger; level = computed from sum(amount)
-- ============================================

ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS settings JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE TABLE IF NOT EXISTS public.quests (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  kind VARCHAR(10) NOT NULL CHECK (kind IN ('daily', 'main', 'side')),
  source VARCHAR(10) NOT NULL DEFAULT 'system' CHECK (source IN ('schedule', 'manual', 'system')),
  title TEXT NOT NULL,
  xp INT NOT NULL DEFAULT 0,
  quest_date DATE,
  due_at TIMESTAMPTZ,
  done_at TIMESTAMPTZ,
  meta JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_quests_user_date ON public.quests(user_id, quest_date);
-- Idempotent daily generation
CREATE UNIQUE INDEX IF NOT EXISTS uq_quests_daily
  ON public.quests(user_id, kind, quest_date, title) WHERE kind = 'daily';

CREATE TABLE IF NOT EXISTS public.xp_events (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  amount INT NOT NULL,
  reason TEXT NOT NULL,
  quest_id UUID REFERENCES public.quests(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_xp_events_user_created ON public.xp_events(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_xp_events_user_reason ON public.xp_events(user_id, reason);

ALTER TABLE public.quests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.xp_events ENABLE ROW LEVEL SECURITY;

-- Reads are client-side (dashboard); all writes go through the API (service
-- role) so XP can't be forged from the browser.
DROP POLICY IF EXISTS "Users view own quests" ON public.quests;
CREATE POLICY "Users view own quests" ON public.quests
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users view own xp events" ON public.xp_events;
CREATE POLICY "Users view own xp events" ON public.xp_events
  FOR SELECT USING (auth.uid() = user_id);

CREATE OR REPLACE FUNCTION public.user_xp_total(p_user_id UUID)
RETURNS BIGINT
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(SUM(amount), 0)::bigint FROM public.xp_events WHERE user_id = p_user_id
$$;
REVOKE EXECUTE ON FUNCTION public.user_xp_total(UUID) FROM PUBLIC, anon, authenticated;
